language: go

os:
  - linux
  - osx

go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - tip

before_script:
  - go get -t -v ./...

script:
  - GOOS=linux go build -o /dev/null ./cmd/...
  - GOOS=darwin go build -o /dev/null ./cmd/...
  - GOOS=freebsd go build -o /dev/null ./cmd/...
  - GOOS=windows go build -o /dev/null ./cmd/...
  - GOARCH=386 go build -o /dev/null ./cmd/...

jobs:
  allow_failures:
    - go: tip
