[[constraint]]
  branch = "master"
  name = "github.com/go-gomail/gomail"

[[constraint]]
  name = "github.com/savsgio/atreugo"
  version = "5.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
