smtp:
  host: <host>
  port: <port>
  user: <user>
  password: <password>

rabbitmq:
  host: <host>  # With or without port
  user: <user>
  password: <password>
  queue_name: <queue name>
  exchange_name: <exchange_name>
  exchange_kind: <exchange_kind>
  declare: false  # Create queue and exchange in RabbitMQ automatically (true/false)
